# "SVGGradientElement::gradientUnits": "SVG_UNIT_TYPE" ,
# "SVGPreserveAspectRatio::meetOrSlice": "SVG_MEETORSLICE" ,
# "SVGAnimationElement::restart": "SVG_ANIMATION_RESTART" ,
# "SVGAnimationElement::fill": "SVG_ANIMATION_FILL" ,
# "SVGTextPathElement::spacing": "TEXTPATH_SPACINGTYPE" ,
# "SVGFETurbulenceElement::stitchTiles": "SVG_STITCHTYPE" ,
# "SVGMarkerElement::orientType": "SVG_MARKER_ORIENT" ,

enum_map = {
"SVGFEConvolveMatrixElement::edgeMode": "SVG_EDGEMODE" ,
"SVGTextPathElement::method": "TEXTPATH_METHODTYPE" ,
"SVGTextPathElement::spacing": "TEXTPATH_SPACINGTYPE" ,
"SVGClipPathElement::clipPathUnits": "SVG_UNIT_TYPE" ,
"SVGLength::unitType": "SVG_LENGTHTYPE" ,
"SVGFEMorphologyElement::operator": "SVG_MORPHOLOGY_OPERATOR" ,
"SVGPaint::paintType": "SVG_PAINTTYPE" ,
"SVGTextContentElement::lengthAdjust": "LENGTHADJUST" ,
"SVGPatternElement::patternUnits": "SVG_UNIT_TYPE" ,
"SVGColor::colorType": "SVG_COLORTYPE" ,
"SVGFEBlendElement::mode": "SVG_FEBLEND_MODE" ,
"SVGGradientElement::gradientUnits": "SVG_UNIT_TYPE" ,
"SVGGradientElement::spreadMethod": "SVG_SPREADMETHOD" ,
"SVGComponentTransferFunctionElement::type": "SVG_FECOMPONENTTRANSFER_TYPE" ,
"SVGFETurbulenceElement::stitchTiles": "SVG_STITCHTYPE" ,
"SVGFETurbulenceElement::type": "SVG_TURBULENCE_TYPE" ,
"SVGPreserveAspectRatio::align": "SVG_PRESERVEASPECTRATIO" ,
"SVGPreserveAspectRatio::meetOrSlice": "SVG_MEETORSLICE" ,
"SVGColorProfileRule::renderingIntent": "RENDERING_INTENT" ,
"SVGAnimationElement::attributeType": "SVG_ANIMATION_ATTRIBUTE_TYPE" ,
"SVGAnimationElement::restart": "SVG_ANIMATION_RESTART" ,
"SVGAnimationElement::fill": "SVG_ANIMATION_FILL" ,
"SVGAnimateTransformElement::type": "SVG_ANIMATETRANSFORM_TYPE" ,
"SVGZoomAndPan::zoomAndPan": "SVG_ZOOMANDPAN" ,
"SVGTransform::type": "SVG_TRANSFORM" ,
"SVGPathSeg::pathSegType": "PATHSEG" ,
"SVGFEColorMatrixElement::type": "SVG_FECOLORMATRIX_TYPE" ,
"SVGMaskElement::maskUnits": "SVG_UNIT_TYPE" ,
"SVGFEDisplacementMapElement::xChannelSelector": "SVG_CHANNEL" ,
"SVGFEDisplacementMapElement::yChannelSelector": "SVG_CHANNEL" ,
"SVGFilterElement::filterUnits": "SVG_UNIT_TYPE" ,
"SVGFilterElement::primitiveUnits": "SVG_UNIT_TYPE" ,
"SVGAngle::unitType": "SVG_ANGLETYPE" ,
"SVGColorProfileElement::renderingIntent": "RENDERING_INTENT" ,
"SVGMarkerElement::markerUnits": "SVG_MARKERUNITS" ,
"SVGMarkerElement::orientType": "SVG_MARKER_ORIENT" ,
"SVGLangSpace::xmlspace": "SVG_XML_SPACE" ,
"SVGFECompositeElement::operator": "SVG_FECOMPOSITE_OPERATOR" ,
"SVGURIReference::xlinkType": "SVG_XLINK_TYPE" ,
"SVGURIReference::xlinkShow": "SVG_XLINK_SHOW" ,
"SVGURIReference::xlinkActuate": "SVG_XLINK_ACTUATE",
"SVGAElement::xlinkShow": "SVG_XLINK_SHOW"
}
