import os
import config
import GenFile

def toto(name, cpptype):
    f=GenFile.gfopen(config.genDir+"/SVG%s.hpp"%name, 'w')
    content = '''// generated by makeBasicTypes.py
#ifndef __svg_SVG%s__
#define __svg_SVG%s__

namespace svg {
'''%(name,name)

    content = content + '\ttypedef %s SVG%s;'%(cpptype, name)

    content = content + '''
}

#endif // __svg_SVG%s__
'''%(name)

    f.write(content)


basicTypes={
    'Boolean':'bool',
    'Integer':'int'
    }


for (name, cpptype) in basicTypes.items():
    toto(name, cpptype)






