import os.path
import os
import string
import config
import GenFile

headersDir = config.genDir

def make(name, as_pointer=0):
	f = GenFile.gfopen(os.path.join(headersDir, "SVG%sList.hpp"%name),'w')
	f.write('''// generated by makeList.py
#ifndef __svg_%sList__
#define __svg_%sList__

#include <w3c/svg/SVGList.hpp>
'''%(name,name))

	typename = name
	if as_pointer!=0:
		typename=typename+'*'
	
	f.write('''#include <w3c/svg/SVG%s.hpp>

namespace svg {
   typedef SVGList<SVG%s> SVG%sList;
}

#endif // __svg_%sList__
'''%(name, typename,name, name))


