import os.path
import os
import config
import GenFile

headersDir = config.genDir

def make(name):
	f = GenFile.gfopen(os.path.join(headersDir, "SVGAnimated%s.hpp"%name),'w')
	f.write('''// generated by makeAnimated.py
#ifndef __svg_Animated%s__
#define __svg_Animated%s__

#include <w3c/svg/Animated.hpp>
'''%(name,name))
	
	f.write('''#include <w3c/svg/SVG%s.hpp>

namespace svg {
   typedef Animated<SVG%s> SVGAnimated%s;
}

#endif // __svg_Animated%s__
'''%(name,name,name, name))



