import re, string
import config
import GenFile

colorstxt = open(config.svgl_home+'/share/colors.txt','r').read()

color_re = re.compile("(\w+)\s+rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)")

output='// generated by makeColors.py\n'
beg=0
pos=0
while 1:
    m = color_re.search(colorstxt, beg)
    if m==None:
        break;
    
    beg = m.end()    
    colorname = m.group(1)
    red=int(m.group(2))
    green=int(m.group(3))
    blue=int(m.group(4))

    output = output +'COLORDEF(%s,%s,%s,%s)\n'%(colorname, red,green,blue)


#f = open(config.genDir+"/colors_def.hpp",'w')
f = GenFile.gfopen(config.genDir+"/colors_def.hpp")
f.write(output)
    
